# Generated by Django 5.1 on 2024-08-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0003_transaction_merchant_transaction_scheduled_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='scheduled_time',
        ),
    ]
