# Generated by Django 5.1 on 2024-08-29 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0006_alter_bankstatement_file_bankstmt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_db',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
